version: 0.0
os: linux
files:
  - source: /hello.js
    destination: /home/ec2-user/www
hooks:
  Applicationstart:
    - location: scripts/start_server.sh
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
