version: 0.0
os: linux
files:
  - source: /hello.js
    destination: /home/ec2-user/www
hooks:    
  ApplicationStart:
  - source: /home/ec2-user/.bash_profile
    destination: /home/ec2-user/www
  - location: scripts/run_server
    runas: root
